[workspace]
authors = ["Esteban Ginez. <175813+eginez@users.noreply.github.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "mojo-learning"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]
build = "mojo build src/mojo/hamt.mojo --emit shared-lib -o dist/mojo_hamt.so"
test = "mojo test -I src/mojo tests/mojo/test_hamt.mojo"

[dependencies]
mojo = "<1.0.0"
python = ">=3.12,<3.13"
