[workspace]
authors = ["Esteban Ginez. <175813+eginez@users.noreply.github.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "mojo-learning"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]
build = "mojo build src/mojo/hamt.mojo --emit shared-lib -o dist/mojo_hamt.so"
build-debug = "mojo build -g --debug-info-language Mojo src/mojo/hamt.mojo --emit shared-lib -o dist/mojo_hamt_debug.so"
build-bench = "mkdir -p dist && mojo build -g --debug-info-language Mojo -I src/mojo benchmarks/mojo/bench_numbers.mojo -o dist/bench_numbers"
test = "mojo test -I src/mojo tests/mojo/test_hamt.mojo"
bench = "mojo run -I src/mojo benchmarks/mojo/bench_numbers.mojo insert 10000"
bench-debug = "mojo run -g --debug-info-language Mojo -I src/mojo benchmarks/mojo/bench_numbers.mojo insert 10000"
profile = { cmd = "xcrun xctrace record --template 'Time Profiler' --output hamt_profile.trace --launch -- dist/bench_numbers insert 10000", depends-on = ["build-bench"] }

[dependencies]
mojo = "<1.0.0"
python = ">=3.12,<3.13"
pandas = ">=2.3.3,<3"
asv = ">=0.6.5,<0.7"
