name: Benchmark

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch full history for asv

      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: latest
          cache: true

      - name: Install dependencies
        run: pixi install

      - name: Install conda-build (fix for conda 25.7.0 bug)
        run: conda install -y conda-build

      - name: Create dist directory
        run: mkdir -p dist

      - name: Build Mojo library
        run: pixi run build

      - name: Register machine for asv
        run: pixi run asv machine --yes

      - name: Run benchmarks
        run: |
          pixi run asv run --show-stderr

      - name: Generate benchmark HTML
        run: pixi run asv publish

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./benchmarks/html
          force_orphan: true
